version: '3'

services:
  web_gu:
    image: registry.gitlab.com/unicef-second-chance/lprs-tn-core-gu:v1
    environment:
      - RESET_PASSWORD_LINK
      - DJANGO_ENV=development
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - PA_BASE_URL
      - SITE_DOMAINE_NAME
    volumes:
      - databases:/app/databases
      - uploaded_media:/app/src/media
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1gb
        reservations:
          memory: 256mb
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.scp-gu-staging-back.rule=Host(`${SITE_DOMAINE_NAME}`)"
        - "traefik.http.routers.scp-gu-staging-back.entrypoints=websecure"
        - "traefik.http.routers.scp-gu-staging-back.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.scp-gu-staging-back-srv.loadbalancer.server.port=8080"


networks:
  default:
    external:
      name: traefik-net


volumes:
  uploaded_media:
  databases:
    external:
      name: pm-api_databases
