# Generated by Django 3.1 on 2021-03-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managment', '0003_auto_20210302_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('product', 'order')},
        ),
    ]
