# Generated by Django 3.1 on 2021-03-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managment', '0005_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
